# Generated by Django 5.0.2 on 2024-03-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fileName', models.CharField(max_length=200)),
                ('folderParent', models.IntegerField(default=0)),
                ('file', models.FileField(blank=True, null=True, upload_to='example/')),
                ('filePath', models.CharField(max_length=500)),
                ('userId', models.CharField(max_length=100)),
                ('createdAt', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
