# Generated by Django 5.0.2 on 2024-03-05 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemodel',
            name='filePath',
        ),
        migrations.CreateModel(
            name='FilePaths',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('filePath', models.CharField(max_length=500)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FileApp.filemodel')),
            ],
        ),
    ]
