# Generated by Django 5.0.2 on 2024-03-29 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FileApp', '0002_remove_filemodel_filepath_filepaths'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemodel',
            name='file',
        ),
    ]
