# Generated by Django 5.0.2 on 2024-02-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FolderApp', '0002_folder_delete_foldermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolderModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('folderName', models.CharField(max_length=50)),
                ('storage', models.IntegerField(blank=True, null=True)),
                ('userId', models.CharField(max_length=100)),
                ('parentFolder', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
